### ISSUE TITLE
prevent client from being saved

### ISSUE THREAD

**Issue by reduzent** [zhdk/tpf-client#43]
It seems the kiosk-mode doesn't reliably prevent the tpf-client from being saved. Saving the client severely breaks it, because since introduction of the dynamic layout, some parts are created dynamically and get duplicated, when they're saved with the tpf-client patch. This can result in peer names appearing multiple times:

![image](https://user-images.githubusercontent.com/333373/174110089-47535ad3-5906-4796-914b-bf393a9e890b.png)

If this happens, the tpf-client should be thrown away and another should be downloaded.

**Comment by reduzent** [comment]
The issue was fixed in tpf-client-app-build repository https://gitlab.zhdk.ch/TPF/tpf-client-app-builder by setting `Binding False` in kiosk.cfg.

**Comment by joambi** [comment]
Lieber Roman,

Danke für die neusten Informationen!
Ich schaffe es nicht den TPF-Client-aoo selber zu kompilieren )-;
Bin gerade am programmieren der OSMOSIS Geschichte, und habe ein, zwei Fragen an dich.
Können wir heute ab 13:00 mal telefonieren?

Danke dir und liebe Grüsse
Johannes


—
—
Zürcher Hochschule der Künste
Zurich University of the Arts
—
Johannes Schütt
Institute for Computer Music and Sound Technology
—
Pfingstweidstrasse 96, Postfach, 8031 Zürich
Telefon +41 43 446 51 72, Mobile +41 79 786 12 49
***@***.******@***.***>
—
www.zhdk.ch, http://www.icst.net
www.ambisonics.ch
—

Am 16.06.2022 um 17:43 schrieb Roman Haefeli ***@***.******@***.***>>:



It seems the kiosk-mode doesn't reliably prevent the tpf-client from being saved. Saving the client severely breaks it, because since introduction of the dynamic layout, some parts are created dynamically and get duplicated, when they're saved with the tpf-client patch. This can result in peer names appearing multiple times:

[image]<https://user-images.githubusercontent.com/333373/174110089-47535ad3-5906-4796-914b-bf393a9e890b.png>

If this happens, the tpf-client should be thrown away and another should be downloaded.
